#!/bin/bash -l
# Job name:
#SBATCH --job-name=run1Densemble
#
# Processors:
#SBATCH --ntasks=500
#
# Wall clock limit:
#SBATCH --time=04:00:00
#
# qos
#SBATCH --qos=lr_normal
#
#
# Partition:
#SBATCH --partition=lr3


## Run command

#edison
#srun -n 1000 ./run_ensemble "/scratch1/scratchdirs/langhans/opt_ensemble_test/" 19683 "/global/homes/l/langhans/singlecolumn/src_ensemble"

#lrc
#mpirun ./run_ensemble "/global/scratch/langhans/opt_ensemble_test2/" 13310 "/global/home/users/langhans/singlecolumn/src_ensemble"
mpirun ./getrmsetot "/global/scratch/langhans/opt_ensemble_test2/"

